### ISSUE TITLE
Should daemon names be strings or keywords?

### ISSUE THREAD

**Issue by seancorfield** [arohner/lein-daemon#10]
I was using keywords previously but when I upgraded to 0.5.1, I got a null pointer on the `(symbol (:ns info))` call because passing `:foo` as the daemon name seemed to just create a `":foo"` string which failed to match on the `get-in` call that gets the daemon info from the project.

When I changed to using strings in the `:daemon` map and passing `foo` as the daemon name, everything worked fine.

The readme is a bit confusing on this since it shows keywords in the `:daemon` map but also shows `lein daemon start foo` (not a keyword) later on. For me, the latter did not work when the `:daemon` map contained keywords.

Not sure whether this is a bug or a documentation issue?

**Comment by arohner** [comment]
Fixed in 0.5.3
