### ISSUE TITLE
Log files created with leading : in their names

### ISSUE THREAD

**Issue by seancorfield** [arohner/lein-daemon#13]
See my note on pull request #12 :

The log file is still created with a leading : on it. This line should call `name` on `alias` I think: https://github.com/arohner/lein-daemon/blob/master/src/leiningen/daemon.clj#L63

**Comment by arohner** [comment]
Arg. Thanks for the report. I just fixed, and pushed 0.5.4

**Comment by seancorfield** [comment]
Verified. We have lein-daemon 0.5.4 in production now. Thanx!
