### ISSUE TITLE
Allow timeout to be a configurable variable

### ISSUE THREAD

**Issue by alexkehayias** [arohner/lein-daemon#14]
Right now it's set to 5 minutes, but I have a project that is timing out. I've noticed that `lein trampoline` can take awhile compared to `lein run` in my case. If this could be a setting specified in `:daemon` in project.clj it would be helpful as I could extend it. Also those who want a shorter timeout can do that too.

As a workaround for anyone having timeout issues, you can run `nohup bash -c "lein trampoline run"`, but you'll need to kill it off manually.

**Comment by arohner** [comment]
Patch welcome. I don't really have the time to do this myself right now.
